const $=id=>document.getElementById(id);let oldData=null,newData=null,lastDiff=[];

function currentTheme(){return document.documentElement.dataset.theme||'light'}
function updateThemeToggle(){const dark=currentTheme()==='dark',btn=$('themeToggle');if(!btn)return;btn.setAttribute('aria-pressed',String(dark));btn.setAttribute('aria-label',dark?'Switch to light theme':'Switch to dark theme');const icon=btn.querySelector('.theme-icon'),label=btn.querySelector('.theme-label');if(icon)icon.textContent=dark?'☀️':'🌙';if(label)label.textContent=dark?'Light':'Dark'}
function setTheme(theme,remember=true){document.documentElement.dataset.theme=theme;if(remember){try{localStorage.setItem('wc-theme',theme)}catch(e){}}updateThemeToggle()}

function detectDelimiter(text){text=text.replace(/^\uFEFF/,'');const candidates=[',',';','\t'];let best=',',bestScore=-1;for(const d of candidates){const counts=[];let q=false,n=0,hasContent=false;for(let i=0;i<text.length&&counts.length<8;i++){const c=text[i],next=text[i+1];if(q){hasContent=true;if(c==='"'&&next==='"'){i++;continue}if(c==='"')q=false;continue}if(c==='"'){q=true;hasContent=true;continue}if(c===d){n++;hasContent=true;continue}if(c==='\n'){if(hasContent){counts.push(n);n=0;hasContent=false}continue}if(c!=='\r')hasContent=true}if(counts.length<8&&hasContent)counts.push(n);const positive=counts.filter(x=>x>0);if(!positive.length)continue;const freq=new Map();for(const x of positive)freq.set(x,(freq.get(x)||0)+1);const common=Math.max(...freq.values());const consistent=positive.length===counts.length?1:0;const score=consistent*10000+common*100+positive.reduce((a,b)=>a+b,0);if(score>bestScore){bestScore=score;best=d}}return best}
function parseCSV(text){text=text.replace(/^\uFEFF/,'');const delimiter=detectDelimiter(text),rows=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(q){if(c==='"'&&n==='"'){cell+='"';i++}else if(c==='"')q=false;else cell+=c}else if(c==='"')q=true;else if(c===delimiter){row.push(cell);cell=''}else if(c==='\n'){row.push(cell);rows.push(row);row=[];cell=''}else if(c!=='\r')cell+=c}row.push(cell);if(row.some(x=>x!==''))rows.push(row);if(q)throw new Error('The CSV contains an unclosed quoted field.');if(rows.length<2)throw new Error('The CSV needs a header row and at least one data row.');const headers=rows[0].map((h,i)=>h.trim()||`Column ${i+1}`);if(new Set(headers).size!==headers.length)throw new Error('The CSV contains duplicate column names. Please make each header unique.');const dataRows=rows.slice(1).filter(r=>r.some(x=>x.trim()!==''));const badIndex=dataRows.findIndex(r=>r.length!==headers.length);if(badIndex!==-1){const r=dataRows[badIndex];throw new Error(`Row ${badIndex+2} has ${r.length} columns, but the header has ${headers.length}. Please fix the CSV structure before comparing.`)}const data=dataRows.map(r=>Object.fromEntries(headers.map((h,i)=>[h,(r[i]??'').trim()])));return{headers,data,delimiter}}
function formatDuration(ms){if(ms<1000)return `${Math.round(ms)} ms`;const s=ms/1000;return `${s<10?s.toFixed(2):s.toFixed(1)} s`}
async function load(file,side){$('results').classList.add('hidden');const started=performance.now();try{$('status').textContent=`Loading ${side==='old'?'older':'newer'} file…`;await new Promise(requestAnimationFrame);const parsed=parseCSV(await file.text());if(side==='old')oldData=parsed;else newData=parsed;updateReady();const elapsed=performance.now()-started;$(side+'Name').textContent=`${file.name} · ${parsed.data.length} rows · loaded in ${formatDuration(elapsed)}`}catch(e){$(side+'Name').textContent='';if(side==='old')oldData=null;else newData=null;$('settings').classList.add('hidden');$('results').classList.add('hidden');$('status').textContent=e.message}}
function keyProblems(data,key){const seen=new Map(),duplicates=[];let blanks=0;data.forEach((r,i)=>{const v=(r[key]??'').trim();if(!v){blanks++;return}if(seen.has(v)){if(!duplicates.includes(v))duplicates.push(v)}else seen.set(v,i)});return{blanks,duplicates}}
function cachedKeyStats(dataset,key){if(!dataset.keyStats)dataset.keyStats=new Map();if(dataset.keyStats.has(key))return dataset.keyStats.get(key);const seen=new Set(),duplicateSet=new Set(),duplicates=[];let blanks=0,nonblank=0;for(const r of dataset.data){const v=(r[key]??'').trim();if(!v){blanks++;continue}nonblank++;if(seen.has(v)){if(!duplicateSet.has(v)){duplicateSet.add(v);duplicates.push(v)}}else seen.add(v)}const stats={blanks,duplicates,uniqueCount:seen.size,nonblank};dataset.keyStats.set(key,stats);return stats}
function isSafeKey(h,dataset){const p=cachedKeyStats(dataset,h);return p.blanks===0&&p.duplicates.length===0}
function uniquenessScore(h,dataset){const p=cachedKeyStats(dataset,h);return p.nonblank?p.uniqueCount/p.nonblank:0}
function looksLikeIdentityKey(h){return /(^|[_\s-])(id|sku|email|code|key)([_\s-]|$)/.test(h.toLowerCase())}
function scoreKey(h,oldSet,newSet){let s=(uniquenessScore(h,oldSet)+uniquenessScore(h,newSet))/2;if(looksLikeIdentityKey(h))s+=1;if(isSafeKey(h,oldSet)&&isSafeKey(h,newSet))s+=.5;else s-=2;return s}
function possibleRenamedKey(){const oldOnly=oldData.headers.filter(h=>!newData.headers.includes(h)&&looksLikeIdentityKey(h)&&isSafeKey(h,oldData)),newOnly=newData.headers.filter(h=>!oldData.headers.includes(h)&&looksLikeIdentityKey(h)&&isSafeKey(h,newData));if(!oldOnly.length||!newOnly.length)return null;oldOnly.sort((a,b)=>uniquenessScore(b,oldData)-uniquenessScore(a,oldData));newOnly.sort((a,b)=>uniquenessScore(b,newData)-uniquenessScore(a,newData));return{oldKey:oldOnly[0],newKey:newOnly[0]}}
function delimiterName(d){return d===';'?'semicolon':d==='\t'?'tab':'comma'}
function updateReady(){$('settings').classList.add('hidden');$('results').classList.add('hidden');$('compareBtn').disabled=false;if(!oldData||!newData){$('status').textContent='Choose two CSV files to begin.';return}const common=oldData.headers.filter(h=>newData.headers.includes(h));if(!common.length){$('status').textContent='These files have no column names in common.';return}const ranked=common.map(h=>({h,score:scoreKey(h,oldData,newData)})).sort((a,b)=>b.score-a.score).map(x=>x.h),renamed=possibleRenamedKey();$('keyColumn').innerHTML=(renamed?'<option value="" selected disabled>Choose a shared key…</option>':'')+ranked.map(h=>`<option>${escapeHTML(h)}</option>`).join('');$('settings').classList.remove('hidden');const formats=oldData.delimiter===newData.delimiter?`${delimiterName(oldData.delimiter)}-separated CSV`:`${delimiterName(oldData.delimiter)} / ${delimiterName(newData.delimiter)} separated CSVs`;if(renamed){$('compareBtn').disabled=true;$('status').textContent=`Possible key mismatch: ${renamed.oldKey} exists only in the older file, while ${renamed.newKey} exists only in the newer file. Choose a shared key only if it identifies the same records in both files.`;return}$('status').textContent=`Ready. ${common.length} shared columns found. Detected ${formats}. Suggested key: ${ranked[0]}.`}
function escapeHTML(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
async function compare(){const key=$('keyColumn').value;if(!key){$('status').textContent='Choose a shared key column before comparing.';$('results').classList.add('hidden');return}const started=performance.now();$('compareBtn').disabled=true;$('status').textContent=`Comparing using ${key}…`;await new Promise(requestAnimationFrame);try{const op=keyProblems(oldData.data,key),np=keyProblems(newData.data,key);if(op.blanks||np.blanks||op.duplicates.length||np.duplicates.length){const parts=[];if(op.blanks)parts.push(`${op.blanks} blank key${op.blanks===1?'':'s'} in the older file`);if(np.blanks)parts.push(`${np.blanks} blank key${np.blanks===1?'':'s'} in the newer file`);if(op.duplicates.length)parts.push(`duplicate ${key} in the older file: ${op.duplicates.slice(0,5).join(', ')}${op.duplicates.length>5?'…':''}`);if(np.duplicates.length)parts.push(`duplicate ${key} in the newer file: ${np.duplicates.slice(0,5).join(', ')}${np.duplicates.length>5?'…':''}`);$('status').textContent=`Cannot safely compare using ${key}: ${parts.join('; ')}. Choose a unique, non-blank key column.`;$('results').classList.add('hidden');return}const oldMap=new Map(oldData.data.map(r=>[r[key],r])),newMap=new Map(newData.data.map(r=>[r[key],r]));const cols=[...new Set([...oldData.headers,...newData.headers])].filter(c=>c!==key);lastDiff=[];for(const [id,r] of newMap){if(!oldMap.has(id)){lastDiff.push({status:'Added',id,changes:'New record'})}else{const o=oldMap.get(id),changes=cols.filter(c=>(o[c]??'')!==(r[c]??'')).map(c=>({field:c,old:o[c]??'',new:r[c]??''}));lastDiff.push({status:changes.length?'Modified':'Unchanged',id,changes})}}for(const [id] of oldMap)if(!newMap.has(id))lastDiff.push({status:'Removed',id,changes:'Record no longer present'});render(key);buildInsights(key,oldMap,newMap,cols);$('status').textContent=`Compared safely using ${key} in ${formatDuration(performance.now()-started)}.`}finally{$('compareBtn').disabled=!$('keyColumn').value}}
function render(key){const counts={Added:0,Removed:0,Modified:0,Unchanged:0};lastDiff.forEach(x=>counts[x.status]++);for(const s of Object.keys(counts))$(s.toLowerCase()+'Count').textContent=counts[s];$('diffRows').innerHTML=lastDiff.filter(x=>x.status!=='Unchanged').slice(0,500).map(x=>`<tr><td><span class="badge ${x.status.toLowerCase()}">${x.status}</span></td><td><strong>${escapeHTML(x.id||'(blank key)')}</strong><br><small>${escapeHTML(key)}</small></td><td>${Array.isArray(x.changes)?x.changes.map(c=>`<div><strong>${escapeHTML(c.field)}:</strong> ${escapeHTML(c.old||'∅')} → ${escapeHTML(c.new||'∅')}</div>`).join(''):escapeHTML(x.changes)}</td></tr>`).join('')||'<tr><td colspan="3">No changed records. The files match on the selected key.</td></tr>';$('results').classList.remove('hidden');$('results').scrollIntoView({behavior:'smooth',block:'start'})}
function number(v){if(v==null||v==='')return null;let s=String(v).replace(/[$€£%\s]/g,'');if(!s)return null;const comma=s.lastIndexOf(','),dot=s.lastIndexOf('.');if(comma!==-1&&dot!==-1){if(comma>dot)s=s.replace(/\./g,'').replace(',','.');else s=s.replace(/,/g,'')}else if(comma!==-1){const decimals=s.length-comma-1;if(decimals===1||decimals===2)s=s.replace(',','.');else s=s.replace(/,/g,'')}else if(dot!==-1){const parts=s.split('.');if(parts.length>2)s=parts.join('');}const n=Number(s);return Number.isFinite(n)?n:null}
function buildInsights(key,oldMap,newMap,cols){const modified=lastDiff.filter(x=>x.status==='Modified'),added=lastDiff.filter(x=>x.status==='Added').length,removed=lastDiff.filter(x=>x.status==='Removed').length,ins=[];ins.push(`<strong>${modified.length}</strong> existing records changed, <strong>${added}</strong> were added and <strong>${removed}</strong> were removed.`);const fieldCounts={};modified.forEach(x=>x.changes.forEach(c=>fieldCounts[c.field]=(fieldCounts[c.field]||0)+1));const top=Object.entries(fieldCounts).sort((a,b)=>b[1]-a[1]).slice(0,3);if(top.length)ins.push(`Most frequently changed columns: ${top.map(([f,n])=>`<strong>${escapeHTML(f)}</strong> (${n})`).join(', ')}.`);for(const col of cols){let up=0,down=0,totalPct=0,pctN=0;for(const x of modified){const c=x.changes.find(z=>z.field===col);if(!c)continue;const a=number(c.old),b=number(c.new);if(a===null||b===null||a===b)continue;if(b>a)up++;else down++;if(a!==0){totalPct+=(b-a)/Math.abs(a)*100;pctN++}}if(up+down>=2){const avg=pctN?totalPct/pctN:0;ins.push(`<strong>${escapeHTML(col)}</strong>: ${up} increased and ${down} decreased${pctN?`; average change among changed numeric values was ${avg>=0?'+':''}${avg.toFixed(1)}%`:''}.`);if(ins.length>=5)break}}$('insights').innerHTML=ins.map(x=>`<div class="insight">${x}</div>`).join('')}
function csvCell(v){v=String(v??'');if(/^[\t\r\n ]*[=+\-@]/.test(v)||/^[\t\r\n]/.test(v))v="'"+v;return /[",\n]/.test(v)?`"${v.replace(/"/g,'""')}"`:v}
function download(){const rows=[['Status','Record','Changes'],...lastDiff.map(x=>[x.status,x.id,Array.isArray(x.changes)?x.changes.map(c=>`${c.field}: ${c.old} -> ${c.new}`).join(' | '):x.changes])];const blob=new Blob([rows.map(r=>r.map(csvCell).join(',')).join('\n')],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='what-changed-report.csv';a.click();URL.revokeObjectURL(a.href)}
['old','new'].forEach(side=>{const input=$(side+'File'),drop=$(side+'Drop');input.addEventListener('change',()=>input.files[0]&&load(input.files[0],side));['dragenter','dragover'].forEach(e=>drop.addEventListener(e,x=>{x.preventDefault();drop.classList.add('drag')}));['dragleave','drop'].forEach(e=>drop.addEventListener(e,x=>{x.preventDefault();drop.classList.remove('drag')}));drop.addEventListener('drop',e=>{const f=e.dataTransfer.files[0];if(f)load(f,side)})});$('keyColumn').addEventListener('change',()=>{const key=$('keyColumn').value;$('compareBtn').disabled=!key;lastDiff=[];$('results').classList.add('hidden');if(key)$('status').textContent=`Key changed to ${key}. Run the comparison again.`});$('compareBtn').addEventListener('click',compare);$('downloadBtn').addEventListener('click',download);
const themeToggle=$('themeToggle');if(themeToggle){updateThemeToggle();themeToggle.addEventListener('click',()=>setTheme(currentTheme()==='dark'?'light':'dark'))}
try{const mq=matchMedia('(prefers-color-scheme: dark)');mq.addEventListener?.('change',e=>{if(!localStorage.getItem('wc-theme'))setTheme(e.matches?'dark':'light',false)})}catch(e){}
